name: Build and Deploy
on:
  push:
    branches:
      -main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      uses: actions/checkout@v3

      - name: Install frontend packages
      working-directory: ./frontend
      run: npm ci

      - name: Build frontend
      working-directory: ./frontend
      npm run build

      - name: Deploy frontend
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: frontend/dist

      - name: Install backend packages
        working-directory: ./backend
        run: npm ci